export const CREATE_PRODUCT = 'CREATE_PRODUCT';

export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';

export const GET_PRODUCTS = 'GET_PRODUCT';

export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';

export const GET_PRICES = 'GET_PRICES';

export const GET_ATTRIBUTES = 'GET_ATTRIBUTES';

export const GET_PRODUCT_ATTRIBUTES = 'GET_PRODUCT_ATTRIBUTES';

export const CREATE_PRODUCT_ATTRIBUTES_SUCCESS = 'CREATE_PRODUCT_ATTRIBUTES_SUCCESS'; 

export const GET_PRODUCT_TYPES = 'GET_PRODUCT_TYPES';

export const GET_BRAND_PRODUCTS = 'GET_BRAND_PRODUCTS';

export const GET_USERS = 'GET_USERS';

export const GET_DETAIL_USERS = 'GET_DETAIL_USERS';

export const GET_ROLES = 'GET_ROLES';

export const GET_ORDER_PRODUCTS = 'GET_ORDER_PRODUCTS';

export const GET_BLOGS = 'GET_BLOGS';

export const GET_CATEGORY_BLOGS = 'GET_CATEGORY_BLOGS';

export const GET_PRICES_SUCCESS = 'GET_PRICES_SUCCESS';

export const GET_ATTRIBUTES_SUCCESS = 'GET_ATTRIBUTES_SUCCESS';

export const GET_PRODUCT_ATTRIBUTES_SUCCESS = 'GET_PRODUCT_ATTRIBUTES_SUCCESS';

export const GET_PRODUCT_TYPES_SUCCESS = 'GET_PRODUCT_TYPES_SUCCESS';

export const GET_BRAND_PRODUCTS_SUCCESS = 'GET_BRAND_PRODUCTS_SUCCESS';

export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';

export const GET_DETAIL_USERS_SUCCESS = 'GET_DETAIL_USERS_SUCCESS';

export const GET_ROLES_SUCCESS = 'GET_ROLES_SUCCESS';

export const GET_ORDER_PRODUCTS_SUCCESS = 'GET_ORDER_PRODUCTS_SUCCESS';

export const GET_BLOGS_SUCCESS = 'GET_BLOGS_SUCCESS';

export const GET_CATEGORY_BLOGS_SUCCESS = 'GET_CATEGORY_BLOGS_SUCCESS';

export const DELETE_PRODUCT = 'DELETE_PRODUCT';

export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';

export const UPDATE_PRODUCT_ATTRIBUTES = 'UPDATE_PRODUCT_ATTRIBUTES';

export const UPDATE_PRICES = 'UPDATE_PRICES';

export const GET_ORDER_ITEMS = 'GET_ORDER_ITEMS';

export const GET_ORDER_ITEMS_SUCCESS = 'GET_ORDER_ITEMS_SUCCESS';

export const GET_ORDERS = 'GET_ORDERS';

export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';

export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';