const orders = [
    {
        id: 1,
        user_id: 1,
        name_from: "Hung",
        name_to: "Hao",
        address_from: "Thai Binh",
        address_to: "Bac Ninh",
        email: "Haoml@gmail.com",
        phone: "0385474645",
        total_money: 340,
        active: true,
        created_at: "2020/05/29",
    },
    {
        id: 2,
        user_id: 1,
        name_from: "Hung",
        name_to: "Hao",
        address_from: "Thai Binh",
        address_to: "Bac Ninh",
        email: "Haoml@gmail.com",
        phone: "0385474645",
        total_money: 340,
        active: true,
        created_at: "2020/05/29",
    },
    {
        id: 3,
        user_id: 1,
        name_from: "Hung",
        name_to: "Hao",
        address_from: "Thai Binh",
        address_to: "Bac Ninh",
        email: "Haoml@gmail.com",
        phone: "0385474645",
        total_money: 340,
        active: true,
        created_at: "2020/05/29",
    },
    {
        id: 4,
        user_id: 1,
        name_from: "Hung",
        name_to: "Hao",
        address_from: "Thai Binh",
        address_to: "Bac Ninh",
        email: "Haoml@gmail.com",
        phone: "0385474645",
        total_money: 340,
        active: true,
        created_at: "2020/05/29",
    },
    {
        id: 5,
        user_id: 1,
        name_from: "Hung",
        name_to: "Hao",
        address_from: "Thai Binh",
        address_to: "Bac Ninh",
        email: "Haoml@gmail.com",
        phone: "0385474645",
        total_money: 340,
        active: true,
        created_at: "2020/05/29",
    },
    {
        id: 6,
        user_id: 1,
        name_from: "Hung",
        name_to: "Hao",
        address_from: "Thai Binh",
        address_to: "Bac Ninh",
        email: "Haoml@gmail.com",
        phone: "0385474645",
        total_money: 340,
        active: true,
        created_at: "2020/05/29",
    },
    {
        id: 7,
        user_id: 1,
        name_from: "Hung",
        name_to: "Hao",
        address_from: "Thai Binh",
        address_to: "Bac Ninh",
        email: "Haoml@gmail.com",
        phone: "0385474645",
        total_money: 340,
        active: true,
        created_at: "2020/05/29",
    },
    {
        id: 8,
        user_id: 1,
        name_from: "Hung",
        name_to: "Hao",
        address_from: "Thai Binh",
        address_to: "Bac Ninh",
        email: "Haoml@gmail.com",
        phone: "0385474645",
        total_money: 340,
        active: true,
        created_at: "2020/05/29",
    },
    {
        id: 9,
        user_id: 1,
        name_from: "Hung",
        name_to: "Hao",
        address_from: "Thai Binh",
        address_to: "Bac Ninh",
        email: "Haoml@gmail.com",
        phone: "0385474645",
        total_money: 340,
        active: true,
        created_at: "2020/05/29",
    },
    {
        id: 10,
        user_id: 1,
        name_from: "Hung",
        name_to: "Hao",
        address_from: "Thai Binh",
        address_to: "Bac Ninh",
        email: "Haoml@gmail.com",
        phone: "0385474645",
        total_money: 340,
        active: true,
        created_at: "2020/05/29",
    },
    {
        id: 11,
        user_id: 1,
        name_from: "Hung",
        name_to: "Hao",
        address_from: "Thai Binh",
        address_to: "Bac Ninh",
        email: "Haoml@gmail.com",
        phone: "0385474645",
        total_money: 340,
        active: true,
        created_at: "2020/05/29",
    },
    {
        id: 12,
        user_id: 1,
        name_from: "Hung",
        name_to: "Hao",
        address_from: "Thai Binh",
        address_to: "Bac Ninh",
        email: "Haoml@gmail.com",
        phone: "0385474645",
        total_money: 340,
        active: true,
        created_at: "2020/05/29",
    },
    {
        id: 13,
        user_id: 2,
        name_from: "Hai",
        name_to: "Hao",
        address_from: "Thai Binh",
        address_to: "Bac Ninh",
        email: "Haoml@gmail.com",
        phone: "0385474645",
        total_money: 340,
        active: true,
        created_at: "2020/05/29",
    },
];

export default orders;