const orderItems = [
    {
        id: 1,
        order_id: 1,
        product_id: 1,
        size: "M",
        color: "Đỏ",
        quantity: 2,
        created_at: "2020/05/29",
    },
    {
        id: 2,
        order_id: 1,
        product_id: 2,
        size: "L",
        color: "Xanh",
        quantity: 1,
        created_at: "2020/05/29",
    },
    {
        id: 3,
        order_id: 1,
        product_id: 3,
        size: "XS",
        color: "Đen",
        quantity: 2,
        created_at: "2020/05/29",
    },
    {
        id: 4,
        order_id: 2,
        product_id: 2,
        size: "S",
        color: "Trắng",
        quantity: 2,
        created_at: "2020/05/29",
    },
    {
        id: 5,
        order_id: 2,
        product_id: 4,
        size: "X",
        color: "Đen",
        quantity: 4,
        created_at: "2020/05/29",
    },
    {
        id: 6,
        order_id: 2,
        product_id: 6,
        size: "XXL",
        color: "Bạc",
        quantity: 1,
        created_at: "2020/05/29",
    },
    {
        id: 7,
        order_id: 2,
        product_id: 7,
        size: "XXS",
        color: "Đen Bạc",
        quantity: 3,
        created_at: "2020/05/29",
    },
    {
        id: 8,
        order_id: 3,
        product_id: 1,
        size: "X",
        color: "Đen",
        quantity: 1,
        created_at: "2020/05/29",
    },
    {
        id: 9,
        order_id: 3,
        product_id: 2,
        size: "XM",
        color: "Vàng",
        quantity: 3,
        created_at: "2020/05/29",
    },
    {
        id: 10,
        order_id: 3,
        product_id: 8,
        size: "L",
        color: "Cam",
        quantity: 4,
        created_at: "2020/05/29",
    },
    {
        id: 11,
        order_id: 4,
        product_id: 6,
        size: "X",
        color: "Trắng",
        quantity: 1,
        created_at: "2020/05/29",
    },
    {
        id: 12,
        order_id: 4,
        product_id: 1,
        size: "M",
        color: "Đen",
        quantity: 5,
        created_at: "2020/05/29",
    },
    {
        id: 13,
        order_id: 4,
        product_id: 3,
        size: "L",
        color: "Hồng",
        quantity: 4,
        created_at: "2020/05/29",
    },
    {
        id: 14,
        order_id: 4,
        product_id: 2,
        size: "XL",
        color: "Tím",
        quantity: 4,
        created_at: "2020/05/29",
    },
    {
        id: 15,
        order_id: 5,
        product_id: 7,
        size: "XS",
        color: "Đen",
        quantity: 3,
        created_at: "2020/05/29",
    },
    {
        id: 16,
        order_id: 5,
        product_id: 6,
        size: "S",
        color: "Cam",
        quantity: 2,
        created_at: "2020/05/29",
    },
    {
        id: 17,
        order_id: 5,
        product_id: 8,
        size: "XXS",
        color: "Tím",
        quantity: 2,
        created_at: "2020/05/29",
    },
    {
        id: 18,
        order_id: 6,
        product_id: 7,
        size: "M",
        color: "Chàm",
        quantity: 3,
        created_at: "2020/05/29",
    },
    {
        id: 19,
        order_id: 6,
        product_id: 1,
        size: "S",
        color: "Lam",
        quantity: 2,
        created_at: "2020/05/29",
    },
    {
        id: 20,
        order_id: 7,
        product_id: 2,
        size: "XXL",
        color: "Lục",
        quantity: 1,
        created_at: "2020/05/29",
    },
    {
        id: 21,
        order_id: 7,
        product_id: 7,
        size: "XS",
        color: "Cam",
        quantity: 2,
        created_at: "2020/05/29",
    },
    {
        id: 22,
        order_id: 8,
        product_id: 5,
        size: "XXS",
        color: "Xanh",
        quantity: 3,
        created_at: "2020/05/29",
    },
    {
        id: 23,
        order_id: 9,
        product_id: 2,
        size: "S",
        color: "Vàng",
        quantity: 5,
        created_at: "2020/05/29",
    },
    {
        id: 24,
        order_id: 9,
        product_id: 3,
        size: "M",
        color: "Đỏ Đậm",
        quantity: 2,
        created_at: "2020/05/29",
    },
    {
        id: 26,
        order_id: 9,
        product_id: 1,
        size: "M",
        color: "Vàng",
        quantity: 4,
        created_at: "2020/05/29",
    },
    {
        id: 27,
        order_id: 9,
        product_id: 5,
        size: "XS",
        color: "Xanh",
        quantity: 1,
        created_at: "2020/05/29",
    },
    {
        id: 28,
        order_id: 10,
        product_id: 8,
        size: "S",
        color: "Đỏ",
        quantity: 3,
        created_at: "2020/05/29",
    },
    {
        id: 29,
        order_id: 10,
        product_id: 7,
        size: "L",
        color: "Xám",
        quantity: 2,
        created_at: "2020/05/29",
    },
    {
        id: 30,
        order_id: 10,
        product_id: 6,
        size: "M",
        color: "Bạc",
        quantity: 2,
        created_at: "2020/05/29",
    },
    {
        id: 31,
        order_id: 10,
        product_id: 2,
        size: "XS",
        color: "Đen",
        quantity: 1,
        created_at: "2020/05/29",
    },
    {
        id: 32,
        order_id: 11,
        product_id: 4,
        size: "XXS",
        color: "Tím",
        quantity: 3,
        created_at: "2020/05/29",
    },
    {
        id: 33,
        order_id: 11,
        product_id: 3,
        size: "S",
        color: "Chàm",
        quantity: 5,
        created_at: "2020/05/29",
    },
    {
        id: 34,
        order_id: 12,
        product_id: 8,
        size: "M",
        color: "Lam",
        quantity: 6,
        created_at: "2020/05/29",
    },
    {
        id: 35,
        order_id: 12,
        product_id: 7,
        size: "L",
        color: "Lục",
        quantity: 3,
        created_at: "2020/05/29",
    },
    {
        id: 36,
        order_id: 12,
        product_id: 6,
        size: "XL",
        color: "Cam",
        quantity: 4,
        created_at: "2020/05/29",
    },
    {
        id: 37,
        order_id: 13,
        product_id: 5,
        size: "XL",
        color: "Vàng",
        quantity: 2,
        created_at: "2020/05/29",
    },
    {
        id: 38,
        order_id: 13,
        product_id: 3,
        size: "XXL",
        color: "Đỏ",
        quantity: 2,
        created_at: "2020/05/29",
    },
    {
        id: 39,
        order_id: 13,
        product_id: 1,
        size: "XXL",
        color: "Đỏ",
        quantity: 5,
        created_at: "2020/05/29",
    },
];

export default orderItems;